[profile.default]
src = "src"
out = "out"
  names = true
sizes = true
optimizer = true
optimizer_runs = 999999
max_test_rejects = 99999
libs = ["lib"]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
